#ifndef QTMATERIALWIDGETS_H
#define QTMATERIALWIDGETS_H

#include <QtCore/qglobal.h>

#if defined(QTMATERIALWIDGETS_EXPORT_LIB)
#    define QTMATERIALWIDGETS_EXPORT Q_DECL_EXPORT
#else
#    define QTMATERIALWIDGETS_EXPORT Q_DECL_IMPORT
#endif

#endif // QTMATERIALWIDGETS_H
